### ISSUE TITLE
Conflict dependencies

### ISSUE THREAD

**Issue by Leael** [dvl-tum/GHOST#13]
when using `conda env create -f env_from_history.yml`
dependencies confict encountered
how to resolve this?

Collecting package metadata (repodata.json): done
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining conflict for urllib3 gdown google-auth-oauthlib requests-oauthlib requests:  35%|▎| 44/127 [06:38<02:52,  2.\ Examining conflict for mkl_fft matfailed                                                                                                                /
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                 /

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python_abi conflicts for:
conda-forge/linux-64::grpcio==1.33.2=py36he0f7d3b_2 -> python[version='>=3.6,<3.7.0a0'] -> python_abi[version='3.10.*|3.6|3.9.*|3.7.*|3.9|3.8.*|3.8|3.7|3.11.*',build='*_cp310|*_cp37m|*_pypy36_pp73|*_cp39|*_pypy39_pp73|*_cp38|*_pypy38_pp73|*_pypy37_pp73|*_cp311']
defaults/linux-64::scipy==1.5.2=py36h0b6359f_0 -> mkl-service[version='>=2,<3.0a0'] -> python_abi[version='3.10.*|3.11.*|3.9|3.8|3.8.*|3.7.*|3.9.*|3.6.*|3.7|3.6',build='*_pypy36_pp73|*_cp37m|*_cp38|*_cp311|*_pypy39_pp73|*_pypy38_pp73|*_cp39|*_cp310|*_cp36m|*_pypy37_pp73']
conda-forge/linux-64::brotlipy==0.7.0=py36he6145b8_1001 -> cffi[version='>=1.0.0'] -> python_abi[version='3.10.*|3.11.*|3.9|3.9.*|3.8.*|3.8|3.7.*|3.7|3.6',build='*_cp37m|*_cp310|*_cp311|*_pypy39_pp73|*_cp39|*_cp38|*_pypy38_pp73|*_pypy37_pp73|*_pypy36_pp73']
...
Package glib conflicts for:
conda-forge/linux-64::dbus==1.13.6=he372182_0 -> glib[version='>=2.58.3,<3.0a0']
anaconda|anaconda/linux-64::glib==2.66.1=h92f7085_0
defaults/linux-64::qt==5.9.7=h5867ecd_1 -> dbus[version='>=1.13.2,<2.0a0'] -> glib[version='>=2.53.6,<2.54.0a0|>=2.53.6,<3.0a0|>=2.56.1,<3.0a0|>=2.63.1,<3.0a0|>=2.56.2,<2.57.0a0|>=2.56.1,<2.57.0a0|>=2.58.3,<3.0a0|>=2.69.1,<3.0a0|>=2.66.1,<3.0a0|>=2.58.2,<2.59.0a0']
defaults/linux-64::gstreamer==1.14.0=h28cd5cc_2 -> glib[version='>=2.66.1,<3.0a0']
defaults/linux-64::gst-plugins-base==1.14.0=hbbd80ab_1 -> glib[version='>=2.56.1,<3.0a0']
defaults/linux-64::gst-plugins-base==1.14.0=hbbd80ab_1 -> gstreamer[version='>=1.14.0,<2.0a0'] -> glib[version='>=2.53.6,<2.54.0a0|>=2.53.6,<3.0a0|>=2.66.1,<3.0a0|>=2.69.1,<3.0a0|>=2.56.1,<2.57.0a0|>=2.76.4,<3.0a0|>=2.76.3,<3.0a0|>=2.76.2,<3.0a0|>=2.74.1,<3.0a0|>=2.74.0,<3.0a0|>=2.72.1,<3.0a0|>=2.70.2,<3.0a0|>=2.58.3,<3.0a0|>=2.58.2,<2.59.0a0']
conda-forge/linux-64::pyqt==5.9.2=py36hcca6a23_4 -> dbus[version='>=1.13.6,<2.0a0'] -> glib[version='>=2.53.6,<2.54.0a0|>=2.53.6,<3.0a0|>=2.56.1,<3.0a0|>=2.56.2,<2.57.0a0|>=2.56.2,<3.0a0|>=2.63.1,<3.0a0|>=2.58.3,<3.0a0|>=2.56.1,<2.57.0a0']
defaults/linux-64::qt==5.9.7=h5867ecd_1 -> glib[version='>=2.56.2,<3.0a0']
anaconda/linux-64::glib==2.66.1=h92f7085_0

Package yaml conflicts for:
conda-forge/noarch::yacs==0.1.6=py_0 -> pyyaml -> yaml[version='>=0.1.7,<0.2.0a0|>=0.2.5,<0.3.0a0|>=0.2.2,<0.3.0a0']
conda-forge/linux-64::yaml==0.2.5=h516909a_0
conda-forge/linux-64::pyyaml==5.3.1=py36he6145b8_1 -> yaml[version='>=0.2.5,<0.3.0a0']
conda-forge|conda-forge/linux-64::yaml==0.2.5=h516909a_0

Package lapsolver conflicts for:
motmetrics -> lapsolver
loopbio|loopbio/linux-64::lapsolver==1.0.2=py36h4af77d5_0
loopbio/linux-64::lapsolver==1.0.2=py36h4af77d5_0

Package chardet conflicts for:
conda-forge|conda-forge/linux-64::chardet==4.0.0=py36h5fab9bb_1
conda-forge/noarch::gdown==3.13.0=pyhd8ed1ab_0 -> requests -> chardet[version='>=3.0.2,<3.1.0|>=3.0.2,<4|>=3.0.2,<5']
conda-forge/linux-64::chardet==4.0.0=py36h5fab9bb_1
conda-forge/noarch::requests-oauthlib==1.3.0=pyh9f0ad1d_0 -> requests[version='>=2.0.0'] -> chardet[version='>=3.0.2,<3.1.0|>=3.0.2,<4|>=3.0.2,<5']
conda-forge/noarch::requests==2.25.1=pyhd3deb0d_0 -> chardet[version='>=3.0.2,<5']

Package pyasn1-modules conflicts for:
conda-forge/noarch::google-auth-oauthlib==0.4.1=py_2 -> google-auth -> pyasn1-modules[version='>=0.0.5,<1dev|>=0.2.1']
conda-forge|conda-forge/noarch::pyasn1-modules==0.2.7=py_0
conda-forge/noarch::pyasn1-modules==0.2.7=py_0
conda-forge/linux-64::google-auth==1.0.1=py36_0 -> pyasn1-modules[version='>=0.0.5,<1dev']

Package fontconfig conflicts for:
defaults/linux-64::qt==5.9.7=h5867ecd_1 -> fontconfig[version='>=2.13.0,<3.0a0']
conda-forge/linux-64::pyqt==5.9.2=py36hcca6a23_4 -> qt=5.9 -> fontconfig[version='>=2.12.6,<3.0a0|>=2.13.0,<3.0a0|>=2.13.1,<3.0a0']
conda-forge/linux-64::fontconfig==2.13.1=he4413a7_1000
conda-forge|conda-forge/linux-64::fontconfig==2.13.1=he4413a7_1000

Package filelock conflicts for:
conda-forge/noarch::filelock==3.0.12=pyh9f0ad1d_0
torchvision==0.8.2 -> pytorch=[build=cuda*] -> filelock
conda-forge/noarch::gdown==3.13.0=pyhd8ed1ab_0 -> filelock
conda-forge|conda-forge/noarch::filelock==3.0.12=pyh9f0ad1d_0

Package enum34 conflicts for:
conda-forge/noarch::oauthlib==3.0.1=py_0 -> cryptography -> enum34
conda-forge/noarch::urllib3==1.26.4=pyhd8ed1ab_0 -> brotlipy[version='>=0.6.0'] -> enum34
conda-forge/linux-64::matplotlib==3.3.3=py36h5fab9bb_0 -> pyqt -> enum34

Package bottleneck conflicts for:
seaborn -> pandas[version='>=0.25'] -> bottleneck[version='>=1.2.1|>=1.3.1|>=1.3.2']
motmetrics -> pandas[version='>=0.23.1'] -> bottleneck[version='>=1.2.1|>=1.3.1|>=1.3.2']

Package urllib3 conflicts for:
conda-forge/noarch::google-auth-oauthlib==0.4.1=py_2 -> google-auth -> urllib3[version='<2.0']
conda-forge/noarch::requests==2.25.1=pyhd3deb0d_0 -> urllib3[version='>=1.21.1,<1.27']
conda-forge/noarch::requests-oauthlib==1.3.0=pyh9f0ad1d_0 -> requests[version='>=2.0.0'] -> urllib3[version='>=1.21.1,<1.22|>=1.21.1,<1.23|>=1.21.1,<1.24|>=1.21.1,<1.25|>=1.21.1,<1.26,!=1.25.0,!=1.25.1|>=1.21.1,<1.27|>=1.21.1,<2|>=1.21.1,<3']
conda-forge/noarch::urllib3==1.26.4=pyhd8ed1ab_0
conda-forge/noarch::gdown==3.13.0=pyhd8ed1ab_0 -> requests -> urllib3[version='>=1.21.1,<1.22|>=1.21.1,<1.23|>=1.21.1,<1.24|>=1.21.1,<1.25|>=1.21.1,<1.26,!=1.25.0,!=1.25.1|>=1.21.1,<1.27|>=1.21.1,<2|>=1.21.1,<3']
conda-forge|conda-forge/noarch::urllib3==1.26.4=pyhd8ed1ab_0

Package zipp conflicts for:
conda-forge/noarch::zipp==3.4.1=pyhd8ed1ab_0
conda-forge/linux-64::importlib-metadata==3.10.1=py36h5fab9bb_0 -> zipp[version='>=0.5']
conda-forge|conda-forge/noarch::zipp==3.4.1=pyhd8ed1ab_0
conda-forge/noarch::markdown==3.3.4=pyhd8ed1ab_0 -> importlib-metadata -> zipp[version='>=0.5']

Package wheel conflicts for:
defaults|defaults/noarch::wheel==0.36.2=pyhd3eb1b0_0
defaults/noarch::wheel==0.36.2=pyhd3eb1b0_0
anaconda/linux-64::pip==20.1.1=py36_1 -> wheel
anaconda/linux-64::python==3.6.12=hcff3b4d_2 -> pip -> wheel

Package openjpeg conflicts for:
conda-forge/linux-64::matplotlib-base==3.3.3=py36he12231b_0 -> pillow[version='>=6.2.0'] -> openjpeg[version='>=2.3.0,<3.0a0|>=2.5.0,<3.0a0|>=2.5.0,<2.6.0a0|>=2.4.0,<3.0.0a0|>=2.4.0,<3.0a0']
torchvision==0.8.2 -> pillow[version='>=4.1.1'] -> openjpeg[version='>=2.3.0,<3.0a0|>=2.5.0,<3.0a0|>=2.5.0,<2.6.0a0|>=2.4.0,<3.0.0a0|>=2.4.0,<3.0a0']

Package libedit conflicts for:
defaults/linux-64::qt==5.9.7=h5867ecd_1 -> sqlite[version='>=3.25.3,<4.0a0'] -> libedit[version='>=3.1.20170329,<3.2.0a0|>=3.1.20181209,<3.2.0a0|>=3.1.20191231,<3.2.0a0']
anaconda|anaconda/linux-64::libedit==3.1.20191231=h14c3975_1
anaconda/linux-64::python==3.6.12=hcff3b4d_2 -> sqlite[version='>=3.33.0,<4.0a0'] -> libedit[version='>=3.1.20191231,<3.2.0a0']
anaconda/linux-64::sqlite==3.33.0=h62c20be_0 -> libedit[version='>=3.1.20191231,<3.2.0a0']
anaconda/linux-64::libedit==3.1.20191231=h14c3975_1

Package kiwisolver conflicts for:
conda-forge|conda-forge/linux-64::kiwisolver==1.3.1=py36h51d7077_0
conda-forge/linux-64::matplotlib-base==3.3.3=py36he12231b_0 -> kiwisolver[version='>=1.0.1']
conda-forge/linux-64::matplotlib==3.3.3=py36h5fab9bb_0 -> matplotlib-base[version='>=3.3.3,<3.3.4.0a0'] -> kiwisolver[version='>=1.0.1']
seaborn -> matplotlib-base[version='>=3.1,!=3.6.1'] -> kiwisolver[version='>=1.0.1']
conda-forge/linux-64::kiwisolver==1.3.1=py36h51d7077_0

.....
  - anaconda/linux-64::lcms2==2.11=h396b838_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - anaconda/linux-64::libedit==3.1.20191231=h14c3975_1 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - anaconda/linux-64::libffi==3.3=he6710b0_2 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - anaconda/linux-64::libpng==1.6.37=hbc83047_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - anaconda/linux-64::libuv==1.40.0=h7b6447c_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - anaconda/linux-64::libxml2==2.9.10=hb55368b_3 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - anaconda/linux-64::mkl_random==1.1.1=py36h0573a6f_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - anaconda/linux-64::ncurses==6.2=he6710b0_1 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - anaconda/linux-64::pandas==1.1.3=py36he6710b0_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - anaconda/linux-64::python==3.6.12=hcff3b4d_2 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - anaconda/linux-64::readline==8.0=h7b6447c_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - anaconda/linux-64::scikit-learn==0.23.2=py36h0573a6f_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - anaconda/linux-64::sip==4.19.8=py36hf484d3e_0 -> libgcc-ng[version='>=7.2.0'] -> __glibc[version='>=2.17']
  - anaconda/linux-64::sqlite==3.33.0=h62c20be_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - anaconda/linux-64::tk==8.6.10=hbc83047_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - anaconda/linux-64::xz==5.2.5=h7b6447c_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - anaconda/linux-64::zlib==1.2.11=h7b6447c_3 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - anaconda/linux-64::zstd==1.4.5=h9ceee32_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - conda-forge/linux-64::brotlipy==0.7.0=py36he6145b8_1001 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - conda-forge/linux-64::c-ares==1.17.1=h36c2ea0_0 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - conda-forge/linux-64::dbus==1.13.6=he372182_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - conda-forge/linux-64::expat==2.2.9=he1b5a44_2 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - conda-forge/linux-64::fontconfig==2.13.1=he4413a7_1000 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - conda-forge/linux-64::grpcio==1.33.2=py36he0f7d3b_2 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - conda-forge/linux-64::icu==58.2=hf484d3e_1000 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - conda-forge/linux-64::kiwisolver==1.3.1=py36h51d7077_0 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - conda-forge/linux-64::libuuid==2.32.1=h14c3975_1000 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - conda-forge/linux-64::libxcb==1.13=h14c3975_1002 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - conda-forge/linux-64::matplotlib-base==3.3.3=py36he12231b_0 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - conda-forge/linux-64::pcre==8.44=he1b5a44_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - conda-forge/linux-64::pthread-stubs==0.4=h36c2ea0_1001 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - conda-forge/linux-64::pyqt==5.9.2=py36hcca6a23_4 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - conda-forge/linux-64::pyyaml==5.3.1=py36he6145b8_1 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - conda-forge/linux-64::tornado==6.1=py36h1d69622_0 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - conda-forge/linux-64::xorg-libxau==1.0.9=h14c3975_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - conda-forge/linux-64::xorg-libxdmcp==1.1.3=h516909a_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - conda-forge/linux-64::yaml==0.2.5=h516909a_0 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - conda-forge/noarch::google-auth-oauthlib==0.4.1=py_2 -> click -> __unix
  - conda-forge/noarch::google-auth-oauthlib==0.4.1=py_2 -> click -> __win
  - conda-forge/noarch::urllib3==1.26.4=pyhd8ed1ab_0 -> pysocks[version='>=1.5.6,<2.0,!=1.5.7'] -> __unix
  - conda-forge/noarch::urllib3==1.26.4=pyhd8ed1ab_0 -> pysocks[version='>=1.5.6,<2.0,!=1.5.7'] -> __win
  - cudatoolkit=10.2 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - defaults/linux-64::cffi==1.14.5=py36h261ae71_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - defaults/linux-64::gst-plugins-base==1.14.0=hbbd80ab_1 -> gstreamer[version='>=1.14.0,<2.0a0'] -> __glibc[version='>=2.17|>=2.17,<3.0.a0']
  - defaults/linux-64::gstreamer==1.14.0=h28cd5cc_2 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - defaults/linux-64::jpeg==9b=h024ee3a_2 -> libgcc-ng[version='>=7.2.0'] -> __glibc[version='>=2.17']
  - defaults/linux-64::libprotobuf==3.14.0=h8c45485_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - defaults/linux-64::libtiff==4.1.0=h2733197_1 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - defaults/linux-64::lz4-c==1.9.3=h2531618_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - defaults/linux-64::mkl-service==2.3.0=py36he8ac12f_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - defaults/linux-64::mkl_fft==1.2.0=py36h23d657b_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - defaults/linux-64::ninja==1.10.2=py36hff7bd54_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - defaults/linux-64::numpy-base==1.19.2=py36hfa32c7d_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - defaults/linux-64::numpy==1.19.2=py36h54aff64_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - defaults/linux-64::pillow==8.1.0=py36he98fc37_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - defaults/linux-64::protobuf==3.14.0=py36h2531618_1 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - defaults/linux-64::qt==5.9.7=h5867ecd_1 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - defaults/linux-64::scipy==1.5.2=py36h0b6359f_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - loopbio/linux-64::lapsolver==1.0.2=py36h4af77d5_0 -> libstdcxx-ng[version='>=4.9'] -> __glibc[version='>=2.17']
  - openssl -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - pytorch==1.7.1 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - torchvision==0.8.2 -> __glibc[version='>=2.17']
  - torchvision==0.8.2 -> cudatoolkit[version='11.0|11.0.*'] -> __glibc[version='>=2.17,<3.0.a0']

Your installed version is: 2.31

**Comment by timmeinhardt** [comment]
How did u resolve this issue?

**Comment by ParaN3xus** [comment]
How did u resolve this issue?
