### ISSUE TITLE
Why does this error occur?

### ISSUE THREAD

**Issue by henuzt** [dvl-tum/GHOST#15]
When I run ‘’bash scripts/main_17.sh’‘， the following error occurred

Traceback (most recent call last):
  File "/home/zt2004/GHOST/tools/main_track.py", line 7, in <module>
    from src.manager import Manager
ModuleNotFoundError: No module named 'src'

but there is clearly src in my GHOST file
Looking forward to your reply

**Comment by JennySeidenschwarz** [comment]
Hello :) 
Mhm this seems to be related to pytorch packaging. Did you solve the issue? A dirty quick fix could be to move the main_track.py file to GHOST directly and run it from here. I will look into this tho!
