### ISSUE TITLE
About BDD server submission ERROR!

### ISSUE THREAD

**Issue by chongweiliu** [dvl-tum/GHOST#16]
When I submit the json results to the BDD sever, I encounter the following error, do you have any idea about how to fix it?

`
Traceback (most recent call last):
  File "/code/scripts/workers/submission_worker.py", line 511, in run_submission
    submission_metadata=submission_serializer.data,
  File "/tmp/tmph0x25gbz/compute/challenge_data/challenge_1836/main.py", line 82, in evaluate
    bdd100k_config = load_label_config(CFG_FILE)
  File "/usr/local/lib/python3.7/site-packages/scalabel/label/io.py", line 188, in load_label_config
    config = Config(**cfg)
  File "/usr/local/lib/python3.7/site-packages/pydantic/main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 24 validation errors for Config
imageSize
  Field required [type=missing, input_value={'image_size': {'height':... {'name': 'bicycle'}]}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
attributes.0.tagPrefix
  Field required [type=missing, input_value={'name': 'crowd', 'type': 'switch', 'tag': 'c'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
attributes.0.tagSuffixes
  Field required [type=missing, input_value={'name': 'crowd', 'type': 'switch', 'tag': 'c'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
attributes.0.values
  Field required [type=missing, input_value={'name': 'crowd', 'type': 'switch', 'tag': 'c'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.0.subcategories.0.subcategories
  Field required [type=missing, input_value={'name': 'pedestrian'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.0.subcategories.0.color
  Field required [type=missing, input_value={'name': 'pedestrian'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.0.subcategories.1.subcategories
  Field required [type=missing, input_value={'name': 'rider'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.0.subcategories.1.color
  Field required [type=missing, input_value={'name': 'rider'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.0.color
  Field required [type=missing, input_value={'name': 'human', 'subcat...n'}, {'name': 'rider'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.1.subcategories.0.subcategories
  Field required [type=missing, input_value={'name': 'car'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.1.subcategories.0.color
  Field required [type=missing, input_value={'name': 'car'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.1.subcategories.1.subcategories
  Field required [type=missing, input_value={'name': 'truck'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.1.subcategories.1.color
  Field required [type=missing, input_value={'name': 'truck'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.1.subcategories.2.subcategories
  Field required [type=missing, input_value={'name': 'bus'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.1.subcategories.2.color
  Field required [type=missing, input_value={'name': 'bus'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.1.subcategories.3.subcategories
  Field required [type=missing, input_value={'name': 'train'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.1.subcategories.3.color
  Field required [type=missing, input_value={'name': 'train'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.1.color
  Field required [type=missing, input_value={'name': 'vehicle', 'subc...s'}, {'name': 'train'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.2.subcategories.0.subcategories
  Field required [type=missing, input_value={'name': 'motorcycle'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.2.subcategories.0.color
  Field required [type=missing, input_value={'name': 'motorcycle'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.2.subcategories.1.subcategories
  Field required [type=missing, input_value={'name': 'bicycle'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.2.subcategories.1.color
  Field required [type=missing, input_value={'name': 'bicycle'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
categories.2.color
  Field required [type=missing, input_value={'name': 'bike', 'subcate...}, {'name': 'bicycle'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
poseSigmas
  Field required [type=missing, input_value={'image_size': {'height':... {'name': 'bicycle'}]}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
`

**Comment by JennySeidenschwarz** [comment]
Hello :) I'm sorry for the late answer, but unfortunately, I never saw this error before. Did you solve the issue?
