### ISSUE TITLE
cannot run!

### ISSUE THREAD

**Issue by zyiyid** [dvl-tum/GHOST#2]
Cannot find tools.train in manager.py, TrackEvalForAllReID in eval_track_eval.py
![image](https://user-images.githubusercontent.com/37584116/224486529-122d5183-74ca-4ce0-a199-efe3c2d925d7.png)
![image](https://user-images.githubusercontent.com/37584116/224486556-613702e7-a4cb-4b71-9a97-b7fc17e7eb33.png)

**Comment by PhuLai** [comment]
Same. train_net and TrackEvalForAllReID are nowhere to be found. @JennySeidenschwarz please look into it. Thanks.

**Comment by JennySeidenschwarz** [comment]
Good morning :)
I actually thought I would have solved already, but apparently github was not doing what I wanted it to do :( 
Can you checkout src/manager.py again and let me know if it works?
Best,
Jenny

**Comment by PhuLai** [comment]
@JennySeidenschwarz TrackEvalForAllReID module is still missing (eval_track_eval.py) :(

**Comment by JennySeidenschwarz** [comment]
Oh my bad, I'm sorry! It should be TrackEvalForGHOST of course because that is the repo that you have to clone as described in the README.md adapted the code! :)

**Comment by PhuLai** [comment]
Needed to replace TrackEvalForAllReID with TrackEvalForGHOST in some other places as well but I think I got it worked now.
README.md might need an update too (AllReID directory doesn't exist).

**Comment by JennySeidenschwarz** [comment]
Thanks for the update! Will adapt the changes! :)

**Comment by PhuLai** [comment]
oh actually I might have adapted just that one file.
