### ISSUE TITLE
On-the-fly domain adaptation

### ISSUE THREAD

**Issue by lhfabc9** [dvl-tum/GHOST#4]
Hello, I would like to ask whether the On-the-fly domain adaptation in your paper is realized by modifying the BN layer structure？

**Comment by JennySeidenschwarz** [comment]
Thanks for your question! We are not changing the structure of the BN layer but rather take the batch statistics (mean and standard deviation) directly for each timestep :)

**Comment by lhfabc9** [comment]
> Thanks for your question! We are not changing the structure of the BN layer but rather take the batch statistics (mean and standard deviation) directly for each timestep :)

thanks for your answer!By the way ,If I train a custom dataset with your REID code, I can implement On-the-fly domain adaptation without additional operations?

**Comment by lhfabc9** [comment]
> Yes, exactly :) On-the-fly domain adaptation is something that just happens during evaluation :)

Thank you for your answer！
