### ISSUE TITLE
TrackEvalForAllReID is missing!

### ISSUE THREAD

**Issue by hahapt** [dvl-tum/GHOST#5]
For the `from TrackEvalForAllReID import trackeval` mentioned in src/eval_track_eval.py, here is no TrackEvalForAllReID module!

**Comment by JennySeidenschwarz** [comment]
Thank you for the question! I just adapted the code, it has to be `from TrackEvalForGHOST import trackeval` since this is the repository that you have to clone as mentioned in the README.md. Can you re-try if it works now? :)
