### ISSUE TITLE
Is there any demo code?

### ISSUE THREAD

**Issue by hahapt** [dvl-tum/GHOST#6]
I want to try GHOST with my demo video and its detections, how can I do that?

**Comment by JennySeidenschwarz** [comment]
Hello and thank you for your question :) All you have to do is bring you video and detections in the same format as the datasets. This means within the dataset directory you need the following structure:

datasets/
    - YourDataset
        - val
              - YourVideo
                    - Img1.jpg
                    - Img2.jpg
                    - ...
    - detections_GHOST
        - YourDataset
              - val
                    - YourVideo.txt

Please let me know if I can help you any further!

**Comment by abhinavisgood** [comment]
The question is , how i should implement this in the code using some other object detector given output in the form of [ [x1, y1, x2, y2 , conf_score1 ] , [ x12 , y12, x22, y22 , conf_score2 ] . . . ]  by the object detector at hand and i want some way through which i would be able to implement this output into a tracker object and utilize it and get an output in format of bounding [tracker_id : bbox]

in python language 

thanks in advance
