### ISSUE TITLE
Help please , aren't there any exmple code on how to use it on custom object detector and webcam , or realtime video feed

### ISSUE THREAD

**Issue by abhinavisgood** [dvl-tum/GHOST#9]
how i should implement this in the code using some other object detector given output in the form of [ [x1, y1, x2, y2 , conf_score1 ] , [ x12 , y12, x22, y22 , conf_score2 ] . . . ] by the object detector at hand and i want some way through which i would be able to implement this output into a tracker object and utilize it and get an output in format of bounding [tracker_id : bbox]
as well as the velocity of the concerned object.

thanks in advance

**Comment by JennySeidenschwarz** [comment]
Hello :)

you would need to bring you're data into the following format:
`names=[
                    'frame',
                    'id',
                    'bb_left',
                    'bb_top',
                    'bb_width',
                    'bb_height',
                    'conf',
                    'label',
                    'vis',
                    '?'])`

frame, bb_left, bb_top, bb_width, bb_height, and conf you have anyway! For the rest, i.e., id, label, vis, and ? you can put 1 everywhere. The input format is a csv file without header. :)

**Comment by ehsainit** [comment]
it would be great if you could add an example for using the framework on actual videos instead of csv detection data

**Comment by JennySeidenschwarz** [comment]
Hey thanks for the suggestion! However, since we are working in an tracking by detection environment we need detections first :)
